app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

calculadora:
    resource: "@AppBundle/Controller/CalculadoraController.php"
    type:     annotation
    prefix: /calculadora

